name: ruChat
main:  ru.dark32.chat.ruChat
version: 1.0.2
commands:
   g:
      description: Сменить канал на глобальный.
      usage: /<command> 
      permission: ruChat.g
      permission-message: You don't have <permission>
   p:
      description: This is a demo command.
      usage: /<command> [player]
      permission: ruChat.p
      permission-message: You don't have <permission>
   s:
      description: This is a demo command.
      usage: /<command> [player]
      permission: ruChat.a
      permission-message: You don't have <permission>
   h:
      description: This is a demo command.
      usage: /<command> [player]
      permission: ruChat.h
      permission-message: You don't have <permission>
   chat:
      description: This is a demo command.
      usage: /<command> [player]
      permission: ruChat.chat
      permission-message: You don't have <permission>